class Solution(object):
    def simplifyPath(self, path):
        """
        :type path: str
        :rtype: str
        """

        partitioned_stack = path.split("/")
        finalized_stack = []

        for x in range(0, len(partitioned_stack)):
            if partitioned_stack[x] == "" or partitioned_stack[x] == " ":
                continue
            elif partitioned_stack[x] == ".":
                continue
            elif partitioned_stack[x] == "..":
                if finalized_stack:
                    finalized_stack.pop()
            else:
                finalized_stack.append(partitioned_stack[x])

        result_path = ""
        for x in range(0, len(finalized_stack)):
            result_path = result_path + "/" + finalized_stack[x]

        if result_path == "":
            result_path = "/"

        return result_path

# The first approach I took was a character-wise approach. Then I thought, what if directories themselves are in a stack. They could simply
# be separated by '/'.
# Therefore, the first approach was to split the string into a partitioned_stack wherever there was a '/'.
# This would create 4 cases:
# 1) .. (parent)
# 2) . (current)
# 3) ... or more and anything else (directory/file name)
# 4) '' basically just an empty spot generated by splitting
# Now, all we need is one further stack/list (finalized_stack) to append everything we need into.
# For an empty spot, we can just skip that element.
# Same with '.', we can just skip that element since it is the current directory.
# For '..', we need to pop whatever is in the finalized_stack if it's not empty.
# For anything else than those 3 conditions, it means we are looking at the third case. So that can just be a directory itself, and we can
# append it into finalized_stack.
# Once we are done going through the partitioned_stack and have produced the finalized_stack completely, we can just append every element
# followed by a singular slash '/' into the string to be returned.
# If the string happens to be empty, that means we are left with nothing but the root folder, so we will just say it's "/".